broker/urls.py
from django.conf.urls import patterns, include, url
from django.contrib.auth.views import login, logout
from django.conf import settings
from django.contrib import admin
from tastypie.api import Api

from broker_opens import views
from django.views.generic.base import TemplateView
from broker_opens.views import RegistrationView, ActivationView
from broker_opens.api import PropertyResource, AgentResource


v1_api = Api(api_name='v1')
v1_api.register(AgentResource())
v1_api.register(PropertyResource())

admin.autodiscover()

urlpatterns = patterns('',

    url(r'^static/(?P<path>.*)$', 'django.views.static.serve',
        {'document_root': settings.STATIC_ROOT}),
    url(r'^$', 'broker_opens.views.home', name='home'),
    url(r'^(?P<month>\d{2})/(?P<day>\d{2})/(?P<year>\d{2})/(?P<location>.+)/$',
        'broker_opens.views.property_list', name='property_list'),
    url(r'^new/$', 'broker_opens.views.new_broken_open', name='new_broken_open'),
    url(r'^broker_open/(.+)$', 'broker_opens.views.edit_broker_open', name='edit_broker_open'),
    url(r'^delete/(.+)$', 'broker_opens.views.delete_broker_open', name='delete_broker_open'),
    url(r'^my_listings/$', 'broker_opens.views.users_listings', name='users_listings'),
    url(r'^create_listing/$', 'broker_opens.views.create_users_listing', name='create_listings'),
    url(r'^create_listing/(.+)$', 'broker_opens.views.moderator_create_listing', name='moderator_create_listing'),
    url(r'^upload_csv/(.+)$', 'broker_opens.views.upload_csv', name='upload_csv'),
    url(r'^my_info/$', 'broker_opens.views.edit_users_profile', name='edit_profile'),
    url(r'^edit_agent_info/(.+)$', 'broker_opens.views.moderator_edit_users_profile', name='moderator_edit_profile'),
    url(r'^create_agent/$', 'broker_opens.views.moderator_create_user', name='moderator_create_user'),
    url(r'^agent/edit_listing/(.+)$', 'broker_opens.views.edit_listing', name='edit_listing'),
    url(r'^moderator/agents/$', 'broker_opens.views.list_agents', name='agent_list'),
    url(r'^password_reset/$', 'django.contrib.auth.views.password_reset',
        {'template_name': 'password_reset/password_reset_form.html',
         'email_template_name':'password_reset/password_reset_email.html'}, name='password_reset'),
    url(r'^password/reset_done/$', 'django.contrib.auth.views.password_reset_done',
        {'template_name': 'password_reset/password_reset_done.html'}, name='password_reset_done'),
    url(r'^reset/(?P<uidb64>[0-9A-Za-z]+)-(?P<token>.+)/$', 'django.contrib.auth.views.password_reset_confirm',
        {'template_name': 'password_reset/password_reset_confirm.html', 'post_reset_redirect' : '/reset/done/'},
        name='password_reset_confirm'),
    url(r'^reset/done/$', 'django.contrib.auth.views.password_reset_complete',
        {'template_name': 'password_reset/password_reset_complete.html'}),
    url(r'^contact/$', 'broker_opens.views.contact', name='contact'),
    url(r'^thanks/$', 'broker_opens.views.thanks', name='thanks'),
    url(r'^login/$', 'broker_opens.views.log_in', name='login'),
    url(r'^logout/$', logout, {'next_page':'login'}, name='logout'),
    url(r'^account_verification/$', views.verification, name='verifying_account'),
    url(r'^accounts/activate/(?P<activation_key>\w+)/$', ActivationView.as_view(), name='registration_activate'),
    url(r'^accounts/register/$', RegistrationView.as_view(), name='registration_register'),
    url(r'^accounts/activate/complete/$', TemplateView.as_view(template_name='registration/activate.html'), name='registration_activation_complete'),
    url(r'^accounts/register/complete/$', TemplateView.as_view(template_name='registration/registration_complete.html'), name='registration_complete'),
    url(r'^admin/', include(admin.site.urls)),

    ##url(r'^api/', include(v1_api.urls)),
)

broker_opens/models/agent.py
from django.contrib.auth.models import BaseUserManager, AbstractBaseUser, PermissionsMixin
from django.db import models
from django.utils import timezone
from django.core.mail import send_mail


class AgentManager(BaseUserManager):
    def create_user(self, email, password=None, **extra_fields):
        now = timezone.now()
        if not email:
            raise ValueError('The given email must be set')
        user = Agent(email=email, is_staff=False, is_active=True, is_superuser=False, last_login=now, date_joined=now, **extra_fields)
        user.set_password(password)
        user.save(using=self._db)
        return user


    def create_superuser(self, email, password, **extra_fields):
        u = self.create_user(email, password, **extra_fields)
        u.is_staff = True
        u.is_active = True
        u.is_superuser = True
        u.save(using=self._db)
        return u


class Agent(AbstractBaseUser, PermissionsMixin):
    email = models.EmailField(unique=True, max_length=254)
    mls_id = models.CharField(unique=True, max_length=15)
    first_name = models.CharField(db_index=True, blank=True, max_length=50)
    last_name = models.CharField(db_index=True, blank=True, max_length=50)
    office_id = models.CharField(max_length=15)
    office_name = models.CharField(blank=True, max_length=50)
    phone_number = models.CharField(max_length=12)
    name = models.CharField(db_index=True, blank=True, max_length=50)
    is_staff = models.BooleanField(default=False)
    is_moderator = models.BooleanField(default=False)
    is_active = models.BooleanField(default=True)
    date_joined = models.DateTimeField(default=timezone.now)

    objects = AgentManager()

    USERNAME_FIELD = 'email'

    class Meta:
        verbose_name_plural = 'agents'
        app_label = 'broker_opens'
        db_table = 'Agent'

    def get_full_name(self):
        return '%s %s' % (self.first_name, self.last_name)

    def get_short_name(self):
        return self.first_name

    def has_perm(self, perm, obj=None):
        return True

    def has_module_perms(self, app_label):
        return True

    def email_user(self, subject, message, from_email=None, **kwargs):
        send_mail(subject, message, from_email, [self.email], **kwargs)

    def __unicode__(self):
        return self.last_name_first()

    @property
    def username(self):
        return getattr(self, self.USERNAME_FIELD)

    @property
    def name(self):
        return '%s %s' % (self.first_name, self.last_name)

    def last_name_first(self):
        return '%s, %s' % (self.last_name, self.first_name)

    @property
    def user_personal_info_valid(self):
        # Just check that the information exists for now
        if self.first_name and self.last_name and self.office_name and self.phone_number:
            return True
        else:
            return False

broker_opens/models/csv_upload.py
import os.path
from django.db import models
from django.core.files.storage import FileSystemStorage
from broker import settings


fs = FileSystemStorage(location=os.path.join(settings.base.BASE_DIR,"broker_opens","scripts","csv_importer"))

class CsvUpload(models.Model):
    file = models.FileField(storage=fs, upload_to="uploaded")
    details = models.CharField(max_length=255, blank=True)
    dump = models.TextField(blank=True)

    class Meta:
        verbose_name_plural = 'csvuploads'
        app_label = 'broker_opens'
        db_table = 'CsvUpload'

broker_opens/views/broker_open.py
from django.shortcuts import render, get_object_or_404, redirect
from django.template import RequestContext
from django.contrib.auth.decorators import login_required, user_passes_test

from broker_opens.models import BrokerOpen
from broker_opens.forms import EditBrokerOpenForm, NewBrokerOpenForm


def home(request):
    if request.user.is_anonymous():
        broker_opens = BrokerOpen.objects.filter(deleted=False, active=True)\
            .order_by('date','location')
    elif request.user.is_moderator:
        broker_opens = BrokerOpen.objects.filter(deleted=False)\
            .order_by('date','location')
    else:
        broker_opens = BrokerOpen.objects.filter(deleted=False, active=True)\
            .order_by('date','location')

    context = {'broker_opens': broker_opens}
    return render(request, 'broker_opens/home.html', context, context_instance=RequestContext(request))


@login_required
@user_passes_test(lambda x: x.is_moderator)
def new_broken_open(request):
    if request.method == "POST":
        form = NewBrokerOpenForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('/')
    else:
        form = NewBrokerOpenForm()
    context = {'form': form}
    return render(request, 'broker_opens/edit_broker_open.html', context)


@login_required
@user_passes_test(lambda x: x.is_moderator)
def edit_broker_open(request, id):
    broker_open = BrokerOpen.objects.get(pk=id)
    if request.method == "POST":
        form = EditBrokerOpenForm(request.POST)
        if form.is_valid():
            print form.cleaned_data
            broker_open.__dict__.update(form.cleaned_data)
            print broker_open.__dict__
            broker_open.save()
            return redirect('/')
    else:
        form = EditBrokerOpenForm(broker_open.__dict__)
    context = {'broker_open':broker_open, 'form': form}
    return render(request, 'broker_opens/edit_broker_open.html', context)


@login_required
@user_passes_test(lambda x: x.is_moderator)
def delete_broker_open(request, id):
    broker_open = BrokerOpen.objects.get(pk=id)
    broker_open.deleted = True
    broker_open.save()
    return redirect('/')

broker_opens/views/contact.py
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib.auth.decorators import login_required
from django.core.mail import send_mail
from django.conf import settings

from broker_opens.forms import ContactUsForm


def contact(request):
    if request.method == "POST":
        form = ContactUsForm(request.POST)
        if form.is_valid():
            name = form.cleaned_data['name']
            email = form.cleaned_data['email']
            phone = form.cleaned_data['phone']
            newsletter = form.cleaned_data['newsletter']
            body = form.cleaned_data['body']
            subject = 'New Inquiry From Broker Opens Portal'
            message = 'name: ' + name + '\n' + 'phone: ' + phone + '\n' + 'email: ' + email + '\n' + 'subscribe to newsletter?: ' + str(newsletter)
            if not request.user.is_anonymous():
                message += '\nuser ID: %s' % request.user.id
                message += '\nuser name: %s' % request.user.name

            message += '\n\n' + body
            send_mail(subject, message, settings.EMAIL_HOST_USER, ['jasonscotthamilton@gmail.com'])
            return redirect('/thanks/')
    else:
        form = ContactUsForm()
    context = {'form': form}
    return render(request, 'contact/contact.html', context)


def thanks(request):
    return render(request, 'contact/thanks.html')

broker_opens/views/property.py
import datetime
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib.auth.decorators import login_required, user_passes_test
from django.contrib.auth import login, logout, authenticate
from django.http import Http404, HttpResponseRedirect
from django.contrib import messages
from django.db.models import Max
from django.core.mail import send_mail
from django.conf import settings
from django.forms.models import model_to_dict
from django.utils.datastructures import MultiValueDictKeyError
from django.core.urlresolvers import reverse

from broker_opens.models import Agent, BrokerOpen, Property, CsvUpload
from broker_opens.forms import EditAgentProfileForm, BrokerEditListingForm, ModeratorEditListingForm, ContactUsForm, EditBrokerOpenForm, NewBrokerOpenForm
from broker_opens.scripts.csv_importer import file_handler

def property_list(request, day=None, month=None, year=None, location=""):
    date_string = day + '/' + month + '/' + year
    date_object = datetime.datetime.strptime(date_string, "%d/%m/%y").date()
    broker_open = BrokerOpen.objects.get(date__contains=date_object, location__iexact=location.replace('_',' '))
    property_list = broker_open.property_set.all().order_by('sort_order').select_related('listing_agent')
    context = {'broker_open': broker_open, 'property_list': property_list}
    return render(request, 'properties/property_list.html', context)


@login_required
def users_listings(request):
    agent = request.user
    properties = Property.objects.all().filter(listing_agent=agent.id)
    context = {'agent': agent, 'properties': properties}
    return render(request, 'properties/agent_listing.html', context)


def _edit_listing_broker(request, listing):
    if listing.listing_agent.mls_id != request.user.mls_id:
        raise Http404

    if request.method == 'POST':
        form = BrokerEditListingForm(request.POST)
        if form.is_valid():
            listing.__dict__.update(form.cleaned_data)
            listing.edited_by_user = True
            listing.broker_open_id = form.cleaned_data['broker_open'].id
            listing.save()

            messages.add_message(request,messages.INFO, 'Your listing has been updated.')
            return redirect('/my_listings/')
    else:
        form = BrokerEditListingForm(model_to_dict(listing))


    context = {'listing': listing, 'form': form, 'page_title':'Edit Listing - %s'%listing.mls_id}
    return render(request, 'properties/edit_listing_broker.html', context)


def _edit_listing_moderator(request, listing):

    if request.method == 'POST':
        form = ModeratorEditListingForm(request.POST)
        if form.is_valid():
            listing.__dict__.update(form.cleaned_data)
            listing.broker_open_id = form.cleaned_data['broker_open'].id
            listing.save()

            messages.add_message(request,messages.INFO, 'The listing has been updated.')
            return redirect(listing.broker_open.url_to_this)
    else:
        form = ModeratorEditListingForm(model_to_dict(listing))


    context = {'listing': listing, 'form': form, 'page_title':'Edit Listing - %s'%listing.mls_id}
    return render(request, 'properties/edit_listing_moderator.html', context)


@login_required
def edit_listing(request, mls_id):
    listing = get_object_or_404(Property, mls_id=mls_id)
    # make sure user is allowed to edit
    if not request.user.is_moderator:
        return _edit_listing_broker(request, listing)
    else:
        return _edit_listing_moderator(request,listing)



@login_required
def create_users_listing(request):
    if not request.user.user_personal_info_valid:
        messages.add_message(request,messages.INFO, 'Please enter your information before creating a listing.')
        return redirect(reverse('edit_profile'))

    if request.method == 'POST':
        form = BrokerEditListingForm(request.POST)
        if form.is_valid():

            listing = Property.create_property_with_random_id()
            listing.listing_agent_id = request.user.id
            listing.edited_by_user = True
            listing.__dict__.update(form.cleaned_data)
            listing.broker_open_id = form.cleaned_data['broker_open'].id
            listing.sort_order = BrokerOpen.get_next_sort_value(form.cleaned_data['broker_open'].id)
            listing.save()
            messages.add_message(request,messages.INFO, 'Your listing has been created.')
            return redirect('/my_listings/')
    else:
        form = BrokerEditListingForm()
    context = {'form': form, 'page_title':'Create New Listing'}
    return render(request, 'properties/edit_listing_broker.html', context)


@login_required
@user_passes_test(lambda x: x.is_moderator)
def moderator_create_listing(request, broker_open_id):
    broker_open = get_object_or_404(BrokerOpen, pk=broker_open_id)
    if request.method == 'POST':
        form = ModeratorEditListingForm(request.POST)
        if form.is_valid():

            listing = Property.create_property_with_random_id()
            listing.listing_agent_id = request.user.id
            listing.edited_by_user = True
            listing.__dict__.update(form.cleaned_data)
            listing.broker_open_id = form.cleaned_data['broker_open'].id
            listing.sort_order = BrokerOpen.get_next_sort_value(form.cleaned_data['broker_open'].id)
            listing.save()
            messages.add_message(request,messages.INFO, 'Your listing has been created.')
            return redirect('/my_listings/')
    else:
        form = ModeratorEditListingForm(initial={'broker_open':broker_open})
    context = {'form': form, 'page_title':'Create New Listing'}
    return render(request, 'properties/edit_listing_moderator.html', context)


@login_required
@user_passes_test(lambda x: x.is_moderator)
def upload_csv(request, broker_open_id):
    broker_open = get_object_or_404(BrokerOpen, pk=broker_open_id)
    if request.method == 'POST':
        message = ""
        try:
            csv = CsvUpload(file=request.FILES['csv_file'])
            csv.save()

            result = file_handler.process_file(request.FILES['csv_file'], broker_open.id)
            if result['success']:
                message += "<p>" + "Your File Was Successfully Imported." + "</p>"
            else:
                message += "<p>" + "An Error Occured While Importing." + "</p>"
            if result['details']:
                message += "<hr><p>" + result['details'] + "</p>"
            if result['dump']:
                message += "<hr><p>" + result['dump'] + "</p>"
            csv.save()
            csv.details = result['details']
            csv.dump = result['dump']
            csv.save()
        except MultiValueDictKeyError:
            message += "<p>" + "Please Upload a File" + "</p>"

        except:
            message += "<p>" + "An Unknown Error Occured" + "</p>"

        messages.add_message(request,messages.INFO, message)


    return redirect(broker_open.url_to_this)

broker_opens/templates/users/agents_list.html
{% extends "base.html" %}

{% block title %}Agents list{% endblock %}

{% block content %}
  <style>
  .agent-page{min-height:650px;}
  .modify-open-button{margin-top:2px;}
  </style>
    <div class="container agent-page">
        <div class="row">
            <div class="col-md-12">
                <h2>Agents</h2>
            </div>
        </div>
        <br />

        <div class="row">
            <div class="col-md-12">
                 <a href="{% url 'moderator_create_user' %}" class="btn btn-primary">Create New Agent</a>
                {% if agents %}
                <table class="table table-striped">
                <thead>
                    <tr>
                        <th>Name</th>
                        <th>Email</th>
                        <th>MLS ID</th>
                        <th></th>
                        <th></th>
                    </tr>
                </thead>
                <tbody>
                {% for agent in agents %}
                    <tr>
                        <td>{{ agent.name }}</td>
                        <td>{{ agent.email }}</td>
                        <td>{{ agent.mls_id }}</td>
                        <td>{% if agent.is_active %}<span class="glyphicon glyphicon-user"></span>{% endif %}</td>
                        <td><a href="{% url 'moderator_edit_profile' agent.mls_id %}" class="btn btn-primary btn-xs"><span class="glyphicon glyphicon-pencil modify-open-button"></a></td>
                    </tr>
                {% endfor %}
                </tbody>
                </table>
                {% else %}
                     <p class="lead">No Users Registered.</p>
                {% endif %}


            </div>

        </div>


    </div>

{% endblock %}

broker_opens/templates/users/create_agent.html
{% extends "base.html" %}

{% block title %}Edit Agent Profile{% endblock %}

{% block content %}
    <style>
    #edit_profile .form-group input{
      font-size:200%;
      height:200%;
    }

    </style>

    <div class="container">
        <div class="col-md-8 col-md-offset-2">


            <form method="POST" action="" id="edit_profile">
                {% if user.is_moderator %}
                <div class="row">

                </div>
                <hr>
                {% endif %}
                <div class="row">
                    <div class="col-sm-5">
                        <div class="form-group{% if form.mls_id.errors %} has-error{% endif %}">
                            <label class="control-label" for="id_mls_id">MLS ID*</label>
                            <input type="text" class="form-control" id="id_mls_id" name="mls_id" value="{{ form.mls_id.value|default:"" }}">
                            {% if form.mls_id.errors %}
                            {% for error in form.mls_id.errors %}
                                <span class="help-block">{{ error }}</span>
                            {% endfor %}
                            {% endif %}
                        </div>
                    </div>

                    <div class="col-sm-5">
                        <div class="form-group{% if form.email.errors %} has-error{% endif %}">
                            <label class="control-label" for="id_email">Email*</label>
                            <input type="text" class="form-control" id="id_email" name="email" value="{{ form.email.value|default:"" }}">
                            {% if form.email.errors %}
                            {% for error in form.email.errors %}
                                <span class="help-block">{{ error }}</span>
                            {% endfor %}
                            {% endif %}
                        </div>
                    </div>

                    <div class="col-sm-2">
                        <div class="form-group{% if form.id_active.errors %} has-error{% endif %}">
                            <label class="control-label" for="id_is_active">Active?</label>
                        </div>
                        {{ form.is_active }}
                    </div>
                </div>
                <div class="row">
                    <div class="col-sm-5">
                        <div class="form-group{% if form.first_name.errors %} has-error{% endif %}">
                          <label class="control-label" for="id_first_name">First Name</label>
                          <input type="text" class="form-control" id="id_first_name" name="first_name" value="{{ form.first_name.value|default:"" }}">
                          {% if form.first_name.errors %}
                          {% for error in form.first_name.errors %}
                              <span class="help-block">{{ error }}</span>
                          {% endfor %}
                          {% endif %}
                        </div>
                    </div>

                    <div class="col-sm-7">
                        <div class="form-group{% if form.last_name.errors %} has-error{% endif %}">
                          <label class="control-label" for="id_last_name">Last Name</label>
                          <input type="text" class="form-control" id="id_last_name" name="last_name" value="{{ form.last_name.value|default:"" }}">
                          {% if form.last_name.errors %}
                          {% for error in form.last_name.errors %}
                              <span class="help-block">{{ error }}</span>
                          {% endfor %}
                          {% endif %}
                        </div>
                    </div>
                </div>

                <div class="row">
                    <div class="col-sm-5">

                        <div class="form-group{% if form.phone_number.errors %} has-error{% endif %}">
                            <label class="control-label" for="id_phone_number">Phone Number</label>
                            <input type="text" class="form-control" id="id_phone_number" name="phone_number" value="{{ form.phone_number.value|default:"" }}">
                            {% if form.phone_number.errors %}
                            {% for error in form.phone_number.errors %}
                                <span class="help-block">{{ error }}</span>
                            {% endfor %}
                            {% endif %}
                        </div>
                    </div>

                    <div class="col-sm-7">
                        <div class="form-group{% if form.office_name.errors %} has-error{% endif %}">
                            <label class="control-label" for="id_office_name">Office Name</label>
                            <input type="text" class="form-control" id="id_office_name" name="office_name" value="{{ form.office_name.value|default:"" }}">
                            {% if form.office_name.errors %}
                            {% for error in form.office_name.errors %}
                                <span class="help-block">{{ error }}</span>
                            {% endfor %}
                            {% endif %}
                        </div>
                    </div>

                {% csrf_token %}
                </div>

                <div class="row">
                    <div class="col-md-12">
                        <input type="submit" value="Save" class="btn btn-primary btn-lg bottom-space">
                    </div>
                </div>

            </form>
        </div>

    </div>
{% endblock %}

broker_opens/templates/users/edit_agent_profile.html
{% extends "base.html" %}

{% block title %}Edit Agent Profile{% endblock %}

{% block content %}
    <style>
    #edit_profile .form-group input{
      font-size:200%;
      height:200%;
    }

    </style>

    <div class="container">
        <div class="col-md-8 col-md-offset-2">
            <div class="col-md-12">
                <div class="row">
                    <h1>My Info</h1>
                    <h4>MLS ID # {{ agent.mls_id }}</h4>
                    {% if user.is_moderator %}
                    <hr>
                    <p>Last Login: {% if agent.last_login == agent.date_joined %}Never{% else %}{{ agent.last_login }}{% endif %}</p>
                    <p>Date Added: {{ agent.date_joined }}</p>
                    <p>Office ID: {{ agent.office_id }}</p>
                    {% endif %}
                </div>
            </div>

            <form method="POST" action="" id="edit_profile">
                {% if user.is_moderator %}
                <div class="row">
                    <div class="col-md-10">
                        <div class="form-group{% if form.email.errors %} has-error{% endif %}">
                          <label class="control-label" for="id_is_active">Email</label>
                          <input type="text" class="form-control" id="id_email" name="email" value="{{ form.email.value|default:"" }}">
                          {% if form.email.errors %}
                          {% for error in form.email.errors %}
                          <span class="help-block">{{ error }}</span>
                          {% endfor %}
                          {% endif %}
                        </div>
                    </div>
                    <div class="col-sm-2">
                        <div class="form-group{% if form.id_active.errors %} has-error{% endif %}">
                            <label class="control-label" for="id_is_active">Active?</label>
                        </div>
                        {{ form.is_active }}
                    </div>
                </div>
                <hr>
                {% endif %}

                <div class="row">
                    <div class="col-sm-5">
                        <div class="form-group{% if form.first_name.errors %} has-error{% endif %}">
                          <label class="control-label" for="id_first_name">First Name</label>
                          <input type="text" class="form-control" id="id_first_name" name="first_name" value="{{ form.first_name.value|default:"" }}">
                          {% if form.first_name.errors %}
                          {% for error in form.first_name.errors %}
                              <span class="help-block">{{ error }}</span>
                          {% endfor %}
                          {% endif %}
                        </div>
                    </div>

                    <div class="col-sm-7">
                        <div class="form-group{% if form.last_name.errors %} has-error{% endif %}">
                          <label class="control-label" for="id_last_name">Last Name</label>
                          <input type="text" class="form-control" id="id_last_name" name="last_name" value="{{ form.last_name.value|default:"" }}">
                          {% if form.last_name.errors %}
                          {% for error in form.last_name.errors %}
                              <span class="help-block">{{ error }}</span>
                          {% endfor %}
                          {% endif %}
                        </div>
                    </div>
                </div>

                <div class="row">
                    <div class="col-sm-5">

                        <div class="form-group{% if form.phone_number.errors %} has-error{% endif %}">
                            <label class="control-label" for="id_phone_number">Phone Number</label>
                            <input type="text" class="form-control" id="id_phone_number" name="phone_number" value="{{ form.phone_number.value|default:"" }}">
                            {% if form.phone_number.errors %}
                            {% for error in form.phone_number.errors %}
                                <span class="help-block">{{ error }}</span>
                            {% endfor %}
                            {% endif %}
                        </div>
                    </div>

                    <div class="col-sm-7">
                        <div class="form-group{% if form.office_name.errors %} has-error{% endif %}">
                            <label class="control-label" for="id_office_name">Office Name</label>
                            <input type="text" class="form-control" id="id_office_name" name="office_name" value="{{ form.office_name.value|default:"" }}">
                            {% if form.office_name.errors %}
                            {% for error in form.office_name.errors %}
                                <span class="help-block">{{ error }}</span>
                            {% endfor %}
                            {% endif %}
                        </div>
                    </div>

                {% csrf_token %}
                </div>

                <div class="row">
                    <div class="col-md-12">
                        <input type="submit" value="Save" class="btn btn-primary btn-lg bottom-space">
                    </div>
                </div>

            </form>
        </div>

    </div>
{% endblock %}