broker/urls.py
from django.conf.urls import patterns, include, url
from django.contrib.auth.views import login, logout
from django.conf import settings
from django.contrib import admin
from tastypie.api import Api

from broker_opens import views
from django.views.generic.base import TemplateView
from broker_opens.views import RegistrationView, ActivationView
from broker_opens.api import PropertyResource, AgentResource


v1_api = Api(api_name='v1')
v1_api.register(AgentResource())
v1_api.register(PropertyResource())

admin.autodiscover()

urlpatterns = patterns('',

    url(r'^static/(?P<path>.*)$', 'django.views.static.serve',
        {'document_root': settings.STATIC_ROOT}),
    url(r'^$', 'broker_opens.views.home', name='home'),
    url(r'^(?P<month>\d{2})/(?P<day>\d{2})/(?P<year>\d{2})/(?P<location>.+)/$',
        'broker_opens.views.property_list', name='property_list'),
    url(r'^new/$', 'broker_opens.views.new_broken_open', name='new_broken_open'),
    url(r'^broker_open/(.+)$', 'broker_opens.views.edit_broker_open', name='edit_broker_open'),
    url(r'^delete/(.+)$', 'broker_opens.views.delete_broker_open', name='delete_broker_open'),
    url(r'^my_listings/$', 'broker_opens.views.users_listings', name='users_listings'),
    url(r'^create_listing/$', 'broker_opens.views.create_users_listing', name='create_listings'),
    url(r'^create_listing/(.+)$', 'broker_opens.views.moderator_create_listing', name='moderator_create_listing'),
    url(r'^upload_csv/(.+)$', 'broker_opens.views.upload_csv', name='upload_csv'),
    url(r'^my_info/$', 'broker_opens.views.edit_users_profile', name='edit_profile'),
    url(r'^edit_agent_info/(.+)$', 'broker_opens.views.moderator_edit_users_profile', name='moderator_edit_profile'),
    url(r'^create_agent/$', 'broker_opens.views.moderator_create_user', name='moderator_create_user'),
    url(r'^agent/edit_listing/(.+)$', 'broker_opens.views.edit_listing', name='edit_listing'),
    url(r'^moderator/agents/$', 'broker_opens.views.list_agents', name='agent_list'),
    url(r'^password_reset/$', 'django.contrib.auth.views.password_reset',
        {'template_name': 'password_reset/password_reset_form.html',
         'email_template_name':'password_reset/password_reset_email.html'}, name='password_reset'),
    url(r'^password/reset_done/$', 'django.contrib.auth.views.password_reset_done',
        {'template_name': 'password_reset/password_reset_done.html'}, name='password_reset_done'),
    url(r'^reset/(?P<uidb64>[0-9A-Za-z]+)-(?P<token>.+)/$', 'django.contrib.auth.views.password_reset_confirm',
        {'template_name': 'password_reset/password_reset_confirm.html', 'post_reset_redirect' : '/reset/done/'},
        name='password_reset_confirm'),
    url(r'^reset/done/$', 'django.contrib.auth.views.password_reset_complete',
        {'template_name': 'password_reset/password_reset_complete.html'}),
    url(r'^contact/$', 'broker_opens.views.contact', name='contact'),
    url(r'^thanks/$', 'broker_opens.views.thanks', name='thanks'),
    url(r'^login/$', 'broker_opens.views.log_in', name='login'),
    url(r'^logout/$', logout, {'next_page':'login'}, name='logout'),
    url(r'^account_verification/$', views.verification, name='verifying_account'),
    url(r'^accounts/activate/(?P<activation_key>\w+)/$', ActivationView.as_view(), name='registration_activate'),
    url(r'^accounts/register/$', RegistrationView.as_view(), name='registration_register'),
    url(r'^accounts/activate/complete/$', TemplateView.as_view(template_name='registration/activate.html'), name='registration_activation_complete'),
    url(r'^accounts/register/complete/$', TemplateView.as_view(template_name='registration/registration_complete.html'), name='registration_complete'),
    url(r'^admin/', include(admin.site.urls)),

    ##url(r'^api/', include(v1_api.urls)),
)

broker_opens/models/agent.py
from django.contrib.auth.models import BaseUserManager, AbstractBaseUser, PermissionsMixin
from django.db import models
from django.utils import timezone
from django.core.mail import send_mail


class AgentManager(BaseUserManager):
    def create_user(self, email, password=None, **extra_fields):
        now = timezone.now()
        if not email:
            raise ValueError('The given email must be set')
        user = Agent(email=email, is_staff=False, is_active=True, is_superuser=False, last_login=now, date_joined=now, **extra_fields)
        user.set_password(password)
        user.save(using=self._db)
        return user


    def create_superuser(self, email, password, **extra_fields):
        u = self.create_user(email, password, **extra_fields)
        u.is_staff = True
        u.is_active = True
        u.is_superuser = True
        u.save(using=self._db)
        return u


class Agent(AbstractBaseUser, PermissionsMixin):
    email = models.EmailField(unique=True, max_length=254)
    mls_id = models.CharField(unique=True, max_length=15)
    first_name = models.CharField(db_index=True, blank=True, max_length=50)
    last_name = models.CharField(db_index=True, blank=True, max_length=50)
    office_id = models.CharField(max_length=15)
    office_name = models.CharField(blank=True, max_length=50)
    phone_number = models.CharField(max_length=12)
    name = models.CharField(db_index=True, blank=True, max_length=50)
    is_staff = models.BooleanField(default=False)
    is_moderator = models.BooleanField(default=False)
    is_active = models.BooleanField(default=True)
    date_joined = models.DateTimeField(default=timezone.now)

    objects = AgentManager()

    USERNAME_FIELD = 'email'

    class Meta:
        verbose_name_plural = 'agents'
        app_label = 'broker_opens'
        db_table = 'Agent'

    def get_full_name(self):
        return '%s %s' % (self.first_name, self.last_name)

    def get_short_name(self):
        return self.first_name

    def has_perm(self, perm, obj=None):
        return True

    def has_module_perms(self, app_label):
        return True

    def email_user(self, subject, message, from_email=None, **kwargs):
        send_mail(subject, message, from_email, [self.email], **kwargs)

    def __unicode__(self):
        return self.last_name_first()

    @property
    def username(self):
        return getattr(self, self.USERNAME_FIELD)

    @property
    def name(self):
        return '%s %s' % (self.first_name, self.last_name)

    def last_name_first(self):
        return '%s, %s' % (self.last_name, self.first_name)

    @property
    def user_personal_info_valid(self):
        # Just check that the information exists for now
        if self.first_name and self.last_name and self.office_name and self.phone_number:
            return True
        else:
            return False

broker_opens/models/broker_open.py
from django.db import models


class BrokerOpen(models.Model):
    date = models.DateField(db_index=True)
    location = models.CharField(db_index=True, max_length=50)
    active = models.BooleanField(db_index=True, default=False)
    deleted = models.BooleanField(db_index=True, default=False)

    @property
    def url_friendly_location(self):
        return self.location.replace(' ','_')

    @property
    def url_to_this(self):
        return '/%s/%s' % (self.date.strftime('%m/%d/%y'), self.url_friendly_location)

    @classmethod
    def get_next_sort_value(cls, id):
        from property import Property
        if Property.objects.filter(broker_open_id=id).count() > 0:
            max = Property.objects.filter(broker_open_id=id).aggregate(models.Max('sort_order'))['sort_order__max']
            return max+1
        else:
            return 1

    class Meta:
        verbose_name_plural = 'brokeropens'
        app_label = 'broker_opens'
        db_table = 'BrokerOpen'

    def __unicode__(self):
        return '%s - %s' % (self.date.strftime('%m/%d/%y'), self.location)

broker_opens/forms.py
from __future__ import unicode_literals
import datetime
from django import forms
from django.forms import ModelForm
from django.utils.translation import ugettext_lazy as _
from django.contrib.auth.forms import ReadOnlyPasswordHashField

from models import Agent, Property, BrokerOpen


class AgentCreationForm(forms.Form):
    """
    A form that creates a user, with no privileges, from the given email and
    password.
    """
    error_messages = {
        'duplicate_email': _("A user with that  email already exists."),
        'password_mismatch': _("The two password fields didn't match."),
    }
    email = forms.EmailField(label=_("Email"),
                             widget=forms.TextInput(attrs={'class':'form-control','placeholder':'Email'}))

    mls_id = forms.CharField(label=_("MLS_ID"),
                             widget=forms.TextInput(attrs={'class':'form-control','placeholder':'MLS ID'}))

    password1 = forms.CharField(label=_("Password"),
                                widget=forms.PasswordInput(attrs={'class':'form-control','placeholder':'Password'}),)

    password2 = forms.CharField(label=_("Password confirmation"),
                                widget=forms.PasswordInput(attrs={'class':'form-control','placeholder':'Confirm Password'}),
                                help_text=_("Enter the same password as above, for verification."),
                                )


    #class Meta:
    #    model = Agent
    #    fields = ("email",)

    def clean_password2(self):
        password1 = self.cleaned_data.get("password1")
        password2 = self.cleaned_data.get("password2")
        if password1 and password2 and password1 != password2:
            raise forms.ValidationError(
                self.error_messages['password_mismatch'])
        return password2

    def save(self, commit=True):
        user = super(AgentCreationForm, self).save(commit=False)
        user.set_password(self.cleaned_data["password1"])
        if commit:
            user.save()
        return user


class AgentChangeForm(forms.ModelForm):
    email = forms.EmailField(label=_("Email"))

    password = ReadOnlyPasswordHashField(label=_("Password"),
                                         help_text=_("Raw passwords are not stored, so there is no way to see "
                                                     "this user's password, but you can change the password "
                                                     "using <a href=\"password/\">this form</a>."))

    class Meta:
        model = Agent

    def __init__(self, *args, **kwargs):
        super(AgentChangeForm, self).__init__(*args, **kwargs)
        f = self.fields.get('user_permissions', None)
        if f is not None:
            f.queryset = f.queryset.select_related('content_type')

    def clean_password(self):
        # Regardless of what the user provides, return the initial value.
        # This is done here, rather than on the field, because the
        # field does not have access to the initial value
        return self.initial["password"]

class PasswordResetRequestForm(forms.Form):
    email = forms.CharField(label=_("Email"))

    def clean_email(self):
        email = self.cleaned_data.get("email")
        if not Agent.objects.filter(email=email).exists():
            raise forms.ValidationError(_("No user with that email exists"))
        return email

class PasswordResetForm(forms.Form):

    password1 = forms.CharField(label=_("Password"),
                                widget=forms.PasswordInput)
    password2 = forms.CharField(label=_("Password confirmation"),
                                widget=forms.PasswordInput)

    def clean_password2(self):
        password1 = self.cleaned_data.get("password1")
        password2 = self.cleaned_data.get("password2")
        if password1 and password2 and password1 != password2:
            raise forms.ValidationError(_("The two passwords did not match"))
        return password2


class EditAgentProfileForm(forms.Form):
    first_name = forms.CharField(max_length=50)
    last_name = forms.CharField(max_length=50)
    phone_number = forms.CharField(max_length=12)
    office_name = forms.CharField(max_length=50)


class CreateAgentProfileForm(forms.Form):
    mls_id = forms.CharField(max_length=15)
    first_name = forms.CharField(required=False, max_length=50)
    last_name = forms.CharField(required=False, max_length=50)
    phone_number = forms.CharField(required=False, max_length=12)
    office_name = forms.CharField(required=False, max_length=50)
    is_active = forms.BooleanField(required=False, widget=forms.CheckboxInput(attrs={'class':'form-control'}))
    email = forms.EmailField()

    def clean_mls_id(self):
        cleaned_data = super(CreateAgentProfileForm,self).clean()
        try:
            Agent.objects.get(mls_id=cleaned_data['mls_id'])
            self._errors['mls_id'] = self.error_class(['This MLS id is already in the system.'])
        except Agent.DoesNotExist:
            pass
        return cleaned_data['mls_id']

    def clean_email(self):
        cleaned_data = super(CreateAgentProfileForm,self).clean()
        try:
            Agent.objects.get(email=cleaned_data['email'])
            self._errors['email'] = self.error_class(['This email id is already in the system.'])
        except Agent.DoesNotExist:
            pass
        return cleaned_data['email']



class ModeratorEditAgentProfileForm(forms.Form):
    first_name = forms.CharField(required=False, max_length=50)
    last_name = forms.CharField(required=False, max_length=50)
    phone_number = forms.CharField(required=False, max_length=12)
    office_name = forms.CharField(required=False, max_length=50)
    is_active = forms.BooleanField(required=False, widget=forms.CheckboxInput(attrs={'class':'form-control'}))
    email = forms.EmailField()

    def set_user_id(self, user_id):
        """
        Here we an pass in user_id data so that we can use it later to validate the user's email address.
        """
        self.user_id = user_id

    def clean_email(self):
        cleaned_data = super(ModeratorEditAgentProfileForm,self).clean()
        try:
            if hasattr(self, 'user_id'):
                Agent.objects.exclude(mls_id=self.user_id).get(email=cleaned_data['email'])
            else:
                Agent.objects.get(email=cleaned_data['email'])
            self._errors['email'] = self.error_class(['This email already exists in the system.'])
        except Agent.DoesNotExist:
            pass
        return cleaned_data['email']


times = [
    ("09:00:00","9:00AM"),
    ("09:15:00","9:15AM"),
    ("09:30:00","9:30AM"),
    ("09:45:00","9:45AM"),
    ("10:00:00","10:00AM"),
    ("10:15:00","10:15AM"),
    ("10:30:00","10:30AM"),
    ("10:45:00","10:45AM"),
    ("11:00:00","11:00AM"),
    ("11:15:00","11:15AM"),
    ("11:30:00","11:30AM"),
    ("11:45:00","11:45AM"),
    ("12:00:00","12:00AM"),
    ("12:15:00","12:15AM"),
    ("12:30:00","12:30AM"),
    ("12:45:00","12:45AM"),
    ("13:00:00","1:00PM"),
    ("13:15:00","1:15PM"),
    ("13:30:00","1:30PM"),
    ("13:45:00","1:45PM"),
    ("14:00:00","2:00PM"),
    ("14:15:00","2:15PM"),
    ("14:30:00","2:30PM"),
    ("14:45:00","2:45PM"),
    ("15:00:00","3:00PM"),
    ("15:15:00","3:15PM"),
    ("15:30:00","3:30PM"),
    ("15:45:00","3:45PM"),


]

property_types = [
    ("SFR","Single Family Residence"),
    ("CND","Condo"),
    ("TWN", "Townhome"),
]


class BrokerEditListingForm(forms.Form):

    address = forms.CharField(max_length=255)
    city = forms.CharField(max_length=75)
    zip_error = 'Please enter a valid CA zip code between 90001 and 96162.'
    zip_code = forms.IntegerField(min_value=90001, max_value=96162, widget=forms.TextInput,\
                                  error_messages={'min_value':zip_error, 'max_value':zip_error})
    beds = forms.IntegerField(max_value=99, min_value=1)
    baths = forms.IntegerField(max_value=99, min_value=1)
    price = forms.IntegerField(max_value=99999999, min_value=1, widget=forms.TextInput)
    property_type = forms.ChoiceField(required=True, choices=property_types, widget=forms.Select(attrs={'class':'form-control'}) )
    broker_open = forms.ModelChoiceField(queryset= BrokerOpen.objects.filter(deleted=False, active=True), empty_label=None, widget=forms.Select(attrs={'class':'form-control'}))
    start_time = forms.ChoiceField(required=False, choices=times, widget=forms.Select(attrs={'class':'form-control'}))
    end_time = forms.ChoiceField(required=False, choices=times, widget=forms.Select(attrs={'class':'form-control'}))

    def clean(self):
        cleaned_data = super(BrokerEditListingForm,self).clean()
        if cleaned_data['start_time'] >= cleaned_data['end_time']:
            self._errors['end_time'] = self._errors['start_time'] = self.error_class(['End time must come after start time.'])
            del cleaned_data['start_time']
        return cleaned_data


class ModeratorEditListingForm(BrokerEditListingForm):
    days_on_market = forms.IntegerField(required=False, max_value=999)
    latitude = forms.DecimalField(required=False, max_value=180, min_value=-180)
    longitude = forms.DecimalField(required=False, max_value=180, min_value=-180)
    edited_by_user = forms.BooleanField(required=False, widget=forms.CheckboxInput(attrs={'class':'form-control'}))
    sort_order = forms.IntegerField()
    listing_agent = forms.ModelChoiceField(queryset= Agent.objects.filter().order_by('last_name'), empty_label=None, widget=forms.Select(attrs={'class':'form-control'}))
    broker_open = forms.ModelChoiceField(queryset= BrokerOpen.objects.filter(deleted=False), empty_label=None, widget=forms.Select(attrs={'class':'form-control'}))



class ContactUsForm(forms.Form):
    name = forms.CharField(max_length=100, required=True)
    email = forms.EmailField(max_length=254, required=True)
    phone = forms.CharField(required=False, max_length=12)

broker_opens/templates/contact/contact.html
{% extends "base.html" %}
{% block content %}

    <div id="contact">
        <div class="container">
            <div class="section_header">
                <h3>Get in touch</h3>
            </div>
            <div class="row contact">
                <p>We’d love to hear from you.</p>

                <form method="POST" action=''>
                    {% csrf_token %}
                    <div class="row form">
                        <div class="col-sm-6 row-col">
                            <div class="box">
                                <input id="id_name" class="name form-control" type="text" name="name" placeholder="Name"
                                        value="{{ form.name.value|default:"" }}">{% if form.name.errors %}
                          {% for error in form.name.errors %}
                              <span class="help-block">{{ error }}</span>
                          {% endfor %}
                          {% endif %}
                                <input id="id_email" class="mail form-control" type="text" name="email" placeholder="Email"
                                        value="{{ form.email.value|default:"" }}">{% if form.email.errors %}
                          {% for error in form.email.errors %}
                              <span class="help-block">{{ error }}</span>
                          {% endfor %}
                          {% endif %}
                                <input id="id_phone" class="phone form-control" type="text" name="phone" placeholder="Phone"
                                        value="{{ form.phone.value|default:"" }}">{% if form.phone.errors %}
                          {% for error in form.phone.errors %}
                              <span class="help-block">{{ error }}</span>
                          {% endfor %}
                          {% endif %}
                            </div>
                        </div>
                        <div class="col-sm-6">
                            <div class="box">
                                <textarea id="id_body" name="body" placeholder="Type a message here..."
                                          class="form-control">{{ form.body.value|default:"" }}</textarea>
                                {% if form.body.errors %}
                          {% for error in form.body.errors %}
                              <span class="help-block">{{ error }}</span>
                          {% endfor %}
                          {% endif %}
                            </div>
                        </div>
                    </div>

                    <div class="row submit">
                        <div class="col-md-5 box">
                            <label class="checkbox">
                                <input id="id_newsletter" name="newsletter" type="checkbox"> Sign up to be contacted when new broker opens are posted.
                            </label>
                        </div>
                        <div class="col-md-3 right">
                            <input type="submit" value="Send your message">
                        </div>
                    </div>
                </form>
            </div>
        </div>


        <div class="map">
            <div class="container">
                <div class="box_wrapp">
                    <div class="box_cont">
                        <div class="head">
                            <h6>Contact</h6>
                        </div>
                        <ul class="street">
                            <li>2301 East Lamar Blvd. Suite 140.</li>
                            <li>City, Arlington. United States,</li>
                            <li>Zip Code, TX 76006.</li>
                            <li class="icon icontop">
                                <span class="contacticos ico1"></span>
                                <span class="text">1 817 274 2933</span>
                            </li>
                            <li class="icon">
                                <span class="contacticos ico2"></span>
                                <a class="text" href="#">bootstrap@twitter.com</a>
                            </li>
                        </ul>

                        <p></p>

                        <a href="#" class="btn">Send Us A Message</a>
                    </div>
                </div>
            </div>

            <iframe width="100%" height="600" frameborder="0" scrolling="no" marginheight="0" marginwidth="0" src="https://maps.google.com/?ie=UTF8&amp;ll=33.83669,-118.4834&amp;spn=0.045157,0.15398&amp;t=m&amp;z=11&amp;output=embed"></iframe>
        </div>
    </div>

{% endblock %}

broker_opens/templates/contact/thanks.html
{% extends "base.html" %}

{% block tittle %}
    Thanks
{% endblock %}


{% block content %}

    <div class="container bottom-space">
        <h1>Thanks for your Message</h1>

        <p>We will answer you as soon as possible.</p>

    </div>

{% endblock %}