broker/urls.py
from django.conf.urls import patterns, include, url
from django.contrib.auth.views import login, logout
from django.conf import settings
from django.contrib import admin
from tastypie.api import Api

from broker_opens import views
from django.views.generic.base import TemplateView
from broker_opens.views import RegistrationView, ActivationView
from broker_opens.api import PropertyResource, AgentResource


v1_api = Api(api_name='v1')
v1_api.register(AgentResource())
v1_api.register(PropertyResource())

admin.autodiscover()

urlpatterns = patterns('',

    url(r'^static/(?P<path>.*)$', 'django.views.static.serve',
        {'document_root': settings.STATIC_ROOT}),
    url(r'^$', 'broker_opens.views.home', name='home'),
    url(r'^(?P<month>\d{2})/(?P<day>\d{2})/(?P<year>\d{2})/(?P<location>.+)/$',
        'broker_opens.views.property_list', name='property_list'),
    url(r'^new/$', 'broker_opens.views.new_broken_open', name='new_broken_open'),
    url(r'^broker_open/(.+)$', 'broker_opens.views.edit_broker_open', name='edit_broker_open'),
    url(r'^delete/(.+)$', 'broker_opens.views.delete_broker_open', name='delete_broker_open'),
    url(r'^my_listings/$', 'broker_opens.views.users_listings', name='users_listings'),
    url(r'^create_listing/$', 'broker_opens.views.create_users_listing', name='create_listings'),
    url(r'^create_listing/(.+)$', 'broker_opens.views.moderator_create_listing', name='moderator_create_listing'),
    url(r'^upload_csv/(.+)$', 'broker_opens.views.upload_csv', name='upload_csv'),
    url(r'^my_info/$', 'broker_opens.views.edit_users_profile', name='edit_profile'),
    url(r'^edit_agent_info/(.+)$', 'broker_opens.views.moderator_edit_users_profile', name='moderator_edit_profile'),
    url(r'^create_agent/$', 'broker_opens.views.moderator_create_user', name='moderator_create_user'),
    url(r'^agent/edit_listing/(.+)$', 'broker_opens.views.edit_listing', name='edit_listing'),
    url(r'^moderator/agents/$', 'broker_opens.views.list_agents', name='agent_list'),
    url(r'^password_reset/$', 'django.contrib.auth.views.password_reset',
        {'template_name': 'password_reset/password_reset_form.html',
         'email_template_name':'password_reset/password_reset_email.html'}, name='password_reset'),
    url(r'^password/reset_done/$', 'django.contrib.auth.views.password_reset_done',
        {'template_name': 'password_reset/password_reset_done.html'}, name='password_reset_done'),
    url(r'^reset/(?P<uidb64>[0-9A-Za-z]+)-(?P<token>.+)/$', 'django.contrib.auth.views.password_reset_confirm',
        {'template_name': 'password_reset/password_reset_confirm.html', 'post_reset_redirect' : '/reset/done/'},
        name='password_reset_confirm'),
    url(r'^reset/done/$', 'django.contrib.auth.views.password_reset_complete',
        {'template_name': 'password_reset/password_reset_complete.html'}),
    url(r'^contact/$', 'broker_opens.views.contact', name='contact'),
    url(r'^thanks/$', 'broker_opens.views.thanks', name='thanks'),
    url(r'^login/$', 'broker_opens.views.log_in', name='login'),
    url(r'^logout/$', logout, {'next_page':'login'}, name='logout'),
    url(r'^account_verification/$', views.verification, name='verifying_account'),
    url(r'^accounts/activate/(?P<activation_key>\w+)/$', ActivationView.as_view(), name='registration_activate'),
    url(r'^accounts/register/$', RegistrationView.as_view(), name='registration_register'),
    url(r'^accounts/activate/complete/$', TemplateView.as_view(template_name='registration/activate.html'), name='registration_activation_complete'),
    url(r'^accounts/register/complete/$', TemplateView.as_view(template_name='registration/registration_complete.html'), name='registration_complete'),
    url(r'^admin/', include(admin.site.urls)),

    ##url(r'^api/', include(v1_api.urls)),
)

broker_opens/models/agent.py
from django.contrib.auth.models import BaseUserManager, AbstractBaseUser, PermissionsMixin
from django.db import models
from django.utils import timezone
from django.core.mail import send_mail


class AgentManager(BaseUserManager):
    def create_user(self, email, password=None, **extra_fields):
        now = timezone.now()
        if not email:
            raise ValueError('The given email must be set')
        user = Agent(email=email, is_staff=False, is_active=True, is_superuser=False, last_login=now, date_joined=now, **extra_fields)
        user.set_password(password)
        user.save(using=self._db)
        return user


    def create_superuser(self, email, password, **extra_fields):
        u = self.create_user(email, password, **extra_fields)
        u.is_staff = True
        u.is_active = True
        u.is_superuser = True
        u.save(using=self._db)
        return u


class Agent(AbstractBaseUser, PermissionsMixin):
    email = models.EmailField(unique=True, max_length=254)
    mls_id = models.CharField(unique=True, max_length=15)
    first_name = models.CharField(db_index=True, blank=True, max_length=50)
    last_name = models.CharField(db_index=True, blank=True, max_length=50)
    office_id = models.CharField(max_length=15)
    office_name = models.CharField(blank=True, max_length=50)
    phone_number = models.CharField(max_length=12)
    name = models.CharField(db_index=True, blank=True, max_length=50)
    is_staff = models.BooleanField(default=False)
    is_moderator = models.BooleanField(default=False)
    is_active = models.BooleanField(default=True)
    date_joined = models.DateTimeField(default=timezone.now)

    objects = AgentManager()

    USERNAME_FIELD = 'email'

    class Meta:
        verbose_name_plural = 'agents'
        app_label = 'broker_opens'
        db_table = 'Agent'

    def get_full_name(self):
        return '%s %s' % (self.first_name, self.last_name)

    def get_short_name(self):
        return self.first_name

    def has_perm(self, perm, obj=None):
        return True

    def has_module_perms(self, app_label):
        return True

    def email_user(self, subject, message, from_email=None, **kwargs):
        send_mail(subject, message, from_email, [self.email], **kwargs)

    def __unicode__(self):
        return self.last_name_first()

    @property
    def username(self):
        return getattr(self, self.USERNAME_FIELD)

    @property
    def name(self):
        return '%s %s' % (self.first_name, self.last_name)

    def last_name_first(self):
        return '%s, %s' % (self.last_name, self.first_name)

    @property
    def user_personal_info_valid(self):
        # Just check that the information exists for now
        if self.first_name and self.last_name and self.office_name and self.phone_number:
            return True
        else:
            return False

broker_opens/models/broker_open.py
from django.db import models


class BrokerOpen(models.Model):
    date = models.DateField(db_index=True)
    location = models.CharField(db_index=True, max_length=50)
    active = models.BooleanField(db_index=True, default=False)
    deleted = models.BooleanField(db_index=True, default=False)

    @property
    def url_friendly_location(self):
        return self.location.replace(' ','_')

    @property
    def url_to_this(self):
        return '/%s/%s' % (self.date.strftime('%m/%d/%y'), self.url_friendly_location)

    @classmethod
    def get_next_sort_value(cls, id):
        from property import Property
        if Property.objects.filter(broker_open_id=id).count() > 0:
            max = Property.objects.filter(broker_open_id=id).aggregate(models.Max('sort_order'))['sort_order__max']
            return max+1
        else:
            return 1

    class Meta:
        verbose_name_plural = 'brokeropens'
        app_label = 'broker_opens'
        db_table = 'BrokerOpen'

    def __unicode__(self):
        return '%s - %s' % (self.date.strftime('%m/%d/%y'), self.location)

broker_opens/models/csv_upload.py
import os.path
from django.db import models
from django.core.files.storage import FileSystemStorage
from broker import settings


fs = FileSystemStorage(location=os.path.join(settings.base.BASE_DIR,"broker_opens","scripts","csv_importer"))

class CsvUpload(models.Model):
    file = models.FileField(storage=fs, upload_to="uploaded")
    details = models.CharField(max_length=255, blank=True)
    dump = models.TextField(blank=True)

    class Meta:
        verbose_name_plural = 'csvuploads'
        app_label = 'broker_opens'
        db_table = 'CsvUpload'

broker_opens/views/broker_open.py
from django.shortcuts import render, get_object_or_404, redirect
from django.template import RequestContext
from django.contrib.auth.decorators import login_required, user_passes_test

from broker_opens.models import BrokerOpen
from broker_opens.forms import EditBrokerOpenForm, NewBrokerOpenForm


def home(request):
    if request.user.is_anonymous():
        broker_opens = BrokerOpen.objects.filter(deleted=False, active=True)\
            .order_by('date','location')
    elif request.user.is_moderator:
        broker_opens = BrokerOpen.objects.filter(deleted=False)\
            .order_by('date','location')
    else:
        broker_opens = BrokerOpen.objects.filter(deleted=False, active=True)\
            .order_by('date','location')

    context = {'broker_opens': broker_opens}
    return render(request, 'broker_opens/home.html', context, context_instance=RequestContext(request))


@login_required
@user_passes_test(lambda x: x.is_moderator)
def new_broken_open(request):
    if request.method == "POST":
        form = NewBrokerOpenForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('/')
    else:
        form = NewBrokerOpenForm()
    context = {'form': form}
    return render(request, 'broker_opens/edit_broker_open.html', context)


@login_required
@user_passes_test(lambda x: x.is_moderator)
def edit_broker_open(request, id):
    broker_open = BrokerOpen.objects.get(pk=id)
    if request.method == "POST":
        form = EditBrokerOpenForm(request.POST)
        if form.is_valid():
            print form.cleaned_data
            broker_open.__dict__.update(form.cleaned_data)
            print broker_open.__dict__
            broker_open.save()
            return redirect('/')
    else:
        form = EditBrokerOpenForm(broker_open.__dict__)
    context = {'broker_open':broker_open, 'form': form}
    return render(request, 'broker_opens/edit_broker_open.html', context)


@login_required
@user_passes_test(lambda x: x.is_moderator)
def delete_broker_open(request, id):
    broker_open = BrokerOpen.objects.get(pk=id)
    broker_open.deleted = True
    broker_open.save()
    return redirect('/')

broker_opens/views/contact.py
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib.auth.decorators import login_required
from django.core.mail import send_mail
from django.conf import settings

from broker_opens.forms import ContactUsForm


def contact(request):
    if request.method == "POST":
        form = ContactUsForm(request.POST)
        if form.is_valid():
            name = form.cleaned_data['name']
            email = form.cleaned_data['email']
            phone = form.cleaned_data['phone']
            newsletter = form.cleaned_data['newsletter']
            body = form.cleaned_data['body']
            subject = 'New Inquiry From Broker Opens Portal'
            message = 'name: ' + name + '\n' + 'phone: ' + phone + '\n' + 'email: ' + email + '\n' + 'subscribe to newsletter?: ' + str(newsletter)
            if not request.user.is_anonymous():
                message += '\nuser ID: %s' % request.user.id
                message += '\nuser name: %s' % request.user.name

            message += '\n\n' + body
            send_mail(subject, message, settings.EMAIL_HOST_USER, ['jasonscotthamilton@gmail.com'])
            return redirect('/thanks/')
    else:
        form = ContactUsForm()
    context = {'form': form}
    return render(request, 'contact/contact.html', context)


def thanks(request):
    return render(request, 'contact/thanks.html')

broker_opens/views/registration_.py
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib.auth.decorators import login_required
from django.contrib.auth import login, logout, authenticate
from django.contrib.sites.models import RequestSite
from django.contrib.sites.models import Site
from django.contrib import messages
from django.http import Http404, HttpResponseRedirect
from django.db.models import Max, Q
from django.db import IntegrityError
from django.core.mail import send_mail
from django.conf import settings
from django.forms.models import model_to_dict
from django.utils.encoding import force_text
from django.core.urlresolvers import reverse_lazy

from registration import signals
from registration.models import RegistrationProfile
from registration.views import RegistrationView as BaseRegistrationView
from registration.views import ActivationView as BaseActivationView

from broker_opens.models import Agent, BrokerOpen, Property
from broker_opens.forms import (EditAgentProfileForm, BrokerEditListingForm, ContactUsForm,
                  EditBrokerOpenForm, NewBrokerOpenForm, AgentCreationForm)



def verification(request):
    return render(request, 'registration/verification.html')


class RegistrationView(BaseRegistrationView):
    """Overriding django-registration Class Based View to do signup logic"""
    form_class = AgentCreationForm

    def register(self, request, **cleaned_data):

        email, mls_id, password = cleaned_data['email'].lower(), cleaned_data['mls_id'].upper(), cleaned_data['password1']

        if Site._meta.installed:
            site = Site.objects.get_current()
        else:
            site = RequestSite(request)

        try:
            user = Agent.objects.get(Q(email=email) | Q(mls_id=mls_id))
            if user:
                if user.email == email and user.mls_id == mls_id and user.is_active == False:
                    # If user exists in DB and isn't active, create activation Key and send email
                    try:
                        new_user = RegistrationProfile.objects.create_profile(user)
                        new_user.send_activation_email(site)
                        signals.user_registered.send(sender=self.__class__,
                                                 user=new_user,
                                                 request=request)
                        user.set_password(password)
                        user.save()
                    except IntegrityError:
                        pass


                else:
                    mod_emails = []
                    moderators = Agent.objects.filter(is_moderator=True)
                    for moderator in moderators:
                        mod_emails.append(moderator.email)
                    subject = 'User signed up with the same email or MLS ID'
                    message = 'A user signed up with the following information: \n email: ' + email + \
                              '\n mls_id: ' + mls_id + '\n\n Existing User: \n email: ' + \
                              user.email + '\n mls_id: ' + user.mls_id + \
                              "\n\nYou will need to manually mark this user's account as active and have them follow the password reset link to activate this account"
                    send_mail(subject, message, settings.EMAIL_HOST_USER, mod_emails)
                    self.success_url = 'verifying_account'

        except Agent.DoesNotExist:
            user = Agent.objects.create_user(email=email, password=password)
            user.mls_id = mls_id
            user.is_active = False
            user.save()

            #send email to moderator so they can login and confirm user
            mod_emails = []
            moderators = Agent.objects.filter(is_moderator=True)
            for moderator in moderators:
                mod_emails.append(moderator.email)
            subject = 'A new user signed up and needs to be approved.'
            message = 'A user signed up with the following information: \n email: ' + email + '\n mls_id: ' + mls_id +\
                      '\n\nThis user is not recognized so you will need to approve this user manually.'
            send_mail(subject, message, settings.EMAIL_HOST_USER, mod_emails)

            self.success_url = 'verifying_account'

        return user


    def get_success_url(self, request, user):
        """
        Return the name of the URL to redirect to after successful
        user registration.

        """
        if self.success_url:
            #Forcing possible reverse_lazy evaluation
            return force_text(self.success_url)
        return ('registration_complete', (), {})


class ActivationView(BaseActivationView):
    """CBV for activating the user"""

    def activate(self, request, activation_key):
        activated_user = RegistrationProfile.objects.activate_user(activation_key)
        if activated_user:
            signals.user_activated.send(sender=self.__class__,
                                        user=activated_user,
                                        request=request)
        return activated_user


    def get_success_url(self, request, user):
        if user:
            context = {'account': user}
        else:
            context = {}
        success_url = reverse_lazy('registration_activation_complete')
        return (success_url, (), context)

broker_opens/templates/broker_opens/_about.html
    <div id="team">
        <div class="container">
            <div class="section_header">
                <h3>Meet our Team</h3>
            </div>

            <div class="row people">
                <div class="row row1">
                    <div class="col-sm-6 bio_box">
                        <img src="{{ STATIC_URL }}img/ale.png" alt="">
                        <div class="info">
                            <p class="name">Alejandra Galvan Castillo</p>
                            <p class="area">Creative Director</p>
                            <a href="#" class="facebook">
                                <span class="socialicons ico1"></span>
                                <span class="socialicons_h ico1h"></span>
                            </a>
                            <a href="#" class="twitter">
                                <span class="socialicons ico2"></span>
                                <span class="socialicons_h ico2h"></span>
                            </a>
                            <a href="#" class="flickr">
                                <span class="socialicons ico4"></span>
                                <span class="socialicons_h ico4h"></span>
                            </a>
                            <a href="#" class="dribble">
                                <span class="socialicons ico6"></span>
                                <span class="socialicons_h ico6h"></span>
                            </a>
                        </div>
                    </div>

                    <div class="col-sm-6 bio_box bio_boxr">
                        <img src="{{ STATIC_URL }}img/ale.png" alt="">
                        <div class="info">
                            <p class="name">Alejandra Galvan Castillo</p>
                            <p class="area">Creative Director</p>
                            <a href="#" class="facebook">
                                <span class="socialicons ico1"></span>
                                <span class="socialicons_h ico1h"></span>
                            </a>
                            <a href="#" class="twitter">
                                <span class="socialicons ico2"></span>
                                <span class="socialicons_h ico2h"></span>
                            </a>
                            <a href="#" class="flickr">
                                <span class="socialicons ico4"></span>
                                <span class="socialicons_h ico4h"></span>
                            </a>
                            <a href="#" class="dribble">
                                <span class="socialicons ico6"></span>
                                <span class="socialicons_h ico6h"></span>
                            </a>
                        </div>
                    </div>
                </div>

                <div class="row row1">
                    <div class="col-sm-6 bio_box">
                        <img src="{{ STATIC_URL }}img/ale.png" alt="">
                        <div class="info">
                            <p class="name">Alejandra Galvan Castillo</p>
                            <p class="area">Creative Director</p>
                            <a href="#" class="facebook">
                                <span class="socialicons ico1"></span>
                                <span class="socialicons_h ico1h"></span>
                            </a>
                            <a href="#" class="twitter">
                                <span class="socialicons ico2"></span>
                                <span class="socialicons_h ico2h"></span>
                            </a>
                            <a href="#" class="flickr">
                                <span class="socialicons ico4"></span>
                                <span class="socialicons_h ico4h"></span>
                            </a>
                            <a href="#" class="dribble">
                                <span class="socialicons ico6"></span>
                                <span class="socialicons_h ico6h"></span>
                            </a>
                        </div>
                    </div>

                    <div class="col-sm-6 bio_box bio_boxr">
                        <img src="{{ STATIC_URL }}img/ale.png" alt="">
                        <div class="info">
                            <p class="name">Alejandra Galvan Castillo</p>
                            <p class="area">Creative Director</p>
                            <a href="#" class="facebook">
                                <span class="socialicons ico1"></span>
                                <span class="socialicons_h ico1h"></span>
                            </a>
                            <a href="#" class="twitter">
                                <span class="socialicons ico2"></span>
                                <span class="socialicons_h ico2h"></span>
                            </a>
                            <a href="#" class="flickr">
                                <span class="socialicons ico4"></span>
                                <span class="socialicons_h ico4h"></span>
                            </a>
                            <a href="#" class="dribble">
                                <span class="socialicons ico6"></span>
                                <span class="socialicons_h ico6h"></span>
                            </a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

broker_opens/templates/broker_opens/edit_broker_open.html
{% extends "base.html" %}

{% block title %}Edit Broker Open {% endblock %}

{% block content %}
     <div class="container">
        <div class="col-md-6 col-md-offset-3">
            <div class="row">
                <h1>Broken Open</h1>
            </div>
            <div class="row">
                <form method="POST" action="" id="custom_form">
                    {% csrf_token %}
                    <div class="row">
                        <div class="col-sm-10">
                            <div class="form-group{% if form.date.errors %} has-error{% endif %}">
                                <label class="control-label" for="id_date">Date</label>
                                <input type="text" class="form-control" id="id_date" name="date" value="{{ form.date.value|date:"SHORT_DATE_FORMAT"}}" placeholder="MM/DD/YYYY">
                                {% if form.date.errors %}
                                {% for error in form.date.errors %}
                                    <span class="help-block">{{ error }}</span>
                                {% endfor %}
                                {% endif %}
                            </div>
                        </div>

                        <div class="col-sm-2">

                            <div class="form-group">
                                <label class="control-label" for="id_is_active">Active</label>

                            </div>
                            {{ form.active }}
                        </div>





                    </div>
                    <div class="row">
                        <div class="form-group{% if form.location.errors %} has-error{% endif %}">
                            <div class="col-sm-12">
                                <label class="control-label" for="id_location">Location</label>
                                <input type="text" class="form-control" id="id_location" name="location" value="{{ form.location.value|default:"" }}">
                                {% if form.location.errors %}
                                {% for error in form.location.errors %}
                                    <span class="help-block">{{ error }}</span>
                                {% endfor %}
                                {% endif %}
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-12">
                            <input type="submit" value="Save" class="btn btn-primary btn-lg bottom-space">
                        </div>
                    </div>
                </form>
            </div>
        </div>
     </div>
{% endblock %}

broker_opens/templates/broker_opens/home.html
{% extends "base.html" %}
{% load staticfiles %}

{% block title %} Broker Opens {% endblock %}

{% block content %}
<style>
.buttons_area{padding-left:20px;}
.buttons_area .btn{margin-top:-20px;margin-left:5px;}
.modify-open-button{margin-top:2px;}
.not-visible-open{color:grey;margin-left:10px;}

</style>


<div id="aboutus">
    <div class="container">
        <div class="section_header">
            <h3>Upcoming Broker Opens</h3>
        </div>

        {% if broker_opens %}
        <table>
        {% for broker_open in broker_opens %}
            <tr>
              <td>

                <p class="lead"><a href="{% url 'property_list' broker_open.date|date:'m' broker_open.date|date:'d' broker_open.date|date:'y' broker_open.url_friendly_location %}">
                 {{ broker_open.date|date:"SHORT_DATE_FORMAT" }} - {{ broker_open.location }}</a>{% if broker_open.active == False and user.is_moderator%}<span class="glyphicon glyphicon-eye-close not-visible-open"></span>{% endif %}</p>
              </td>
              <td class="buttons_area">
                 {% if user.is_moderator %}
                    <a href="{% url 'edit_broker_open' broker_open.id %}" class="btn btn-primary btn-xs"><span class="glyphicon glyphicon-pencil modify-open-button"></a>
                    <a href="{% url 'delete_broker_open' broker_open.id %}" class="btn btn-danger btn-xs" onclick="return confirm('Are you sure you want to delete this?')"><span class="glyphicon glyphicon-remove modify-open-button"></span></a>
                 {% endif %}

              </td>
            </tr>
        {% endfor %}
        </table>
        {% else %}
            <p class="lead">There are no upcoming broker opens.</p>
        {% endif %}
         {% if user.is_moderator %}
         <div class=col-md-4>
          <div class="row bottom-space">
            <a href="{% url 'new_broken_open' %}" class="btn btn-primary btn-large">Create New</a>
          </div>
        </div>
         {% endif %}

    </div>
</div>

{% comment %}{% include "broker_opens/_about.html" %}{% endcomment %}

{% endblock %}