broker/urls.py
from django.conf.urls import patterns, include, url
from django.contrib.auth.views import login, logout
from django.conf import settings
from django.contrib import admin
from tastypie.api import Api

from broker_opens import views
from django.views.generic.base import TemplateView
from broker_opens.views import RegistrationView, ActivationView
from broker_opens.api import PropertyResource, AgentResource


v1_api = Api(api_name='v1')
v1_api.register(AgentResource())
v1_api.register(PropertyResource())

admin.autodiscover()

urlpatterns = patterns('',

    url(r'^static/(?P<path>.*)$', 'django.views.static.serve',
        {'document_root': settings.STATIC_ROOT}),
    url(r'^$', 'broker_opens.views.home', name='home'),
    url(r'^(?P<month>\d{2})/(?P<day>\d{2})/(?P<year>\d{2})/(?P<location>.+)/$',
        'broker_opens.views.property_list', name='property_list'),
    url(r'^new/$', 'broker_opens.views.new_broken_open', name='new_broken_open'),
    url(r'^broker_open/(.+)$', 'broker_opens.views.edit_broker_open', name='edit_broker_open'),
    url(r'^delete/(.+)$', 'broker_opens.views.delete_broker_open', name='delete_broker_open'),
    url(r'^my_listings/$', 'broker_opens.views.users_listings', name='users_listings'),
    url(r'^create_listing/$', 'broker_opens.views.create_users_listing', name='create_listings'),
    url(r'^create_listing/(.+)$', 'broker_opens.views.moderator_create_listing', name='moderator_create_listing'),
    url(r'^upload_csv/(.+)$', 'broker_opens.views.upload_csv', name='upload_csv'),
    url(r'^my_info/$', 'broker_opens.views.edit_users_profile', name='edit_profile'),
    url(r'^edit_agent_info/(.+)$', 'broker_opens.views.moderator_edit_users_profile', name='moderator_edit_profile'),
    url(r'^create_agent/$', 'broker_opens.views.moderator_create_user', name='moderator_create_user'),
    url(r'^agent/edit_listing/(.+)$', 'broker_opens.views.edit_listing', name='edit_listing'),
    url(r'^moderator/agents/$', 'broker_opens.views.list_agents', name='agent_list'),
    url(r'^password_reset/$', 'django.contrib.auth.views.password_reset',
        {'template_name': 'password_reset/password_reset_form.html',
         'email_template_name':'password_reset/password_reset_email.html'}, name='password_reset'),
    url(r'^password/reset_done/$', 'django.contrib.auth.views.password_reset_done',
        {'template_name': 'password_reset/password_reset_done.html'}, name='password_reset_done'),
    url(r'^reset/(?P<uidb64>[0-9A-Za-z]+)-(?P<token>.+)/$', 'django.contrib.auth.views.password_reset_confirm',
        {'template_name': 'password_reset/password_reset_confirm.html', 'post_reset_redirect' : '/reset/done/'},
        name='password_reset_confirm'),
    url(r'^reset/done/$', 'django.contrib.auth.views.password_reset_complete',
        {'template_name': 'password_reset/password_reset_complete.html'}),
    url(r'^contact/$', 'broker_opens.views.contact', name='contact'),
    url(r'^thanks/$', 'broker_opens.views.thanks', name='thanks'),
    url(r'^login/$', 'broker_opens.views.log_in', name='login'),
    url(r'^logout/$', logout, {'next_page':'login'}, name='logout'),
    url(r'^account_verification/$', views.verification, name='verifying_account'),
    url(r'^accounts/activate/(?P<activation_key>\w+)/$', ActivationView.as_view(), name='registration_activate'),
    url(r'^accounts/register/$', RegistrationView.as_view(), name='registration_register'),
    url(r'^accounts/activate/complete/$', TemplateView.as_view(template_name='registration/activate.html'), name='registration_activation_complete'),
    url(r'^accounts/register/complete/$', TemplateView.as_view(template_name='registration/registration_complete.html'), name='registration_complete'),
    url(r'^admin/', include(admin.site.urls)),

    ##url(r'^api/', include(v1_api.urls)),
)

broker_opens/models/broker_open.py
from django.db import models


class BrokerOpen(models.Model):
    date = models.DateField(db_index=True)
    location = models.CharField(db_index=True, max_length=50)
    active = models.BooleanField(db_index=True, default=False)
    deleted = models.BooleanField(db_index=True, default=False)

    @property
    def url_friendly_location(self):
        return self.location.replace(' ','_')

    @property
    def url_to_this(self):
        return '/%s/%s' % (self.date.strftime('%m/%d/%y'), self.url_friendly_location)

    @classmethod
    def get_next_sort_value(cls, id):
        from property import Property
        if Property.objects.filter(broker_open_id=id).count() > 0:
            max = Property.objects.filter(broker_open_id=id).aggregate(models.Max('sort_order'))['sort_order__max']
            return max+1
        else:
            return 1

    class Meta:
        verbose_name_plural = 'brokeropens'
        app_label = 'broker_opens'
        db_table = 'BrokerOpen'

    def __unicode__(self):
        return '%s - %s' % (self.date.strftime('%m/%d/%y'), self.location)

broker_opens/models/property.py
import random
import string

from django.conf import settings
from django.db import models
from broker_open import BrokerOpen

class Property(models.Model):

    mls_id = models.CharField(primary_key=True, max_length=10)
    start_time = models.TimeField(auto_now=False, auto_now_add=False)
    end_time = models.TimeField(auto_now=False, auto_now_add=False)
    address = models.CharField(max_length=255)
    city = models.CharField(max_length=75)
    zip_code = models.IntegerField(blank=True, max_length=5)
    latitude = models.DecimalField(blank=True, null=True, max_digits=9, decimal_places=6)
    longitude = models.DecimalField(blank=True, null=True, max_digits=9, decimal_places=6)
    beds = models.IntegerField(blank=True, max_length=2)
    baths = models.IntegerField(blank=True, max_length=2)
    price = models.IntegerField(blank=True, max_length=8)
    listing_agent = models.ForeignKey(settings.AUTH_USER_MODEL)
    property_type = models.CharField(blank=True, max_length=150)
    days_on_market = models.IntegerField(blank=True, null=True, max_length=5)
    edited_by_user = models.BooleanField(default=False)
    broker_open = models.ForeignKey(BrokerOpen)
    sort_order = models.IntegerField(max_length=3)

    @classmethod
    def create_property_with_random_id(cls):
        """ Generates a random property id in the form of CUST_XXXXX
        """
        string_valid = False
        while string_valid == False:
            random_chars = ''.join(random.choice(string.ascii_uppercase+string.digits) for x in range(5))
            rand_string = "CUST_" + random_chars
            try:
                cls.objects.get(mls_id=rand_string)
            except:
                string_valid = True
        return cls(mls_id=rand_string)

    def created_by_user(self):
        if "CUST_" in self.mls_id:
            return True
        else:
            return False


    class Meta:
        verbose_name_plural = 'properties'
        app_label = 'broker_opens'
        db_table = 'Property'

broker_opens/views/broker_open.py
from django.shortcuts import render, get_object_or_404, redirect
from django.template import RequestContext
from django.contrib.auth.decorators import login_required, user_passes_test

from broker_opens.models import BrokerOpen
from broker_opens.forms import EditBrokerOpenForm, NewBrokerOpenForm


def home(request):
    if request.user.is_anonymous():
        broker_opens = BrokerOpen.objects.filter(deleted=False, active=True)\
            .order_by('date','location')
    elif request.user.is_moderator:
        broker_opens = BrokerOpen.objects.filter(deleted=False)\
            .order_by('date','location')
    else:
        broker_opens = BrokerOpen.objects.filter(deleted=False, active=True)\
            .order_by('date','location')

    context = {'broker_opens': broker_opens}
    return render(request, 'broker_opens/home.html', context, context_instance=RequestContext(request))


@login_required
@user_passes_test(lambda x: x.is_moderator)
def new_broken_open(request):
    if request.method == "POST":
        form = NewBrokerOpenForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('/')
    else:
        form = NewBrokerOpenForm()
    context = {'form': form}
    return render(request, 'broker_opens/edit_broker_open.html', context)


@login_required
@user_passes_test(lambda x: x.is_moderator)
def edit_broker_open(request, id):
    broker_open = BrokerOpen.objects.get(pk=id)
    if request.method == "POST":
        form = EditBrokerOpenForm(request.POST)
        if form.is_valid():
            print form.cleaned_data
            broker_open.__dict__.update(form.cleaned_data)
            print broker_open.__dict__
            broker_open.save()
            return redirect('/')
    else:
        form = EditBrokerOpenForm(broker_open.__dict__)
    context = {'broker_open':broker_open, 'form': form}
    return render(request, 'broker_opens/edit_broker_open.html', context)


@login_required
@user_passes_test(lambda x: x.is_moderator)
def delete_broker_open(request, id):
    broker_open = BrokerOpen.objects.get(pk=id)
    broker_open.deleted = True
    broker_open.save()
    return redirect('/')

broker_opens/views/contact.py
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib.auth.decorators import login_required
from django.core.mail import send_mail
from django.conf import settings

from broker_opens.forms import ContactUsForm


def contact(request):
    if request.method == "POST":
        form = ContactUsForm(request.POST)
        if form.is_valid():
            name = form.cleaned_data['name']
            email = form.cleaned_data['email']
            phone = form.cleaned_data['phone']
            newsletter = form.cleaned_data['newsletter']
            body = form.cleaned_data['body']
            subject = 'New Inquiry From Broker Opens Portal'
            message = 'name: ' + name + '\n' + 'phone: ' + phone + '\n' + 'email: ' + email + '\n' + 'subscribe to newsletter?: ' + str(newsletter)
            if not request.user.is_anonymous():
                message += '\nuser ID: %s' % request.user.id
                message += '\nuser name: %s' % request.user.name

            message += '\n\n' + body
            send_mail(subject, message, settings.EMAIL_HOST_USER, ['jasonscotthamilton@gmail.com'])
            return redirect('/thanks/')
    else:
        form = ContactUsForm()
    context = {'form': form}
    return render(request, 'contact/contact.html', context)


def thanks(request):
    return render(request, 'contact/thanks.html')

broker_opens/views/property.py
import datetime
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib.auth.decorators import login_required, user_passes_test
from django.contrib.auth import login, logout, authenticate
from django.http import Http404, HttpResponseRedirect
from django.contrib import messages
from django.db.models import Max
from django.core.mail import send_mail
from django.conf import settings
from django.forms.models import model_to_dict
from django.utils.datastructures import MultiValueDictKeyError
from django.core.urlresolvers import reverse

from broker_opens.models import Agent, BrokerOpen, Property, CsvUpload
from broker_opens.forms import EditAgentProfileForm, BrokerEditListingForm, ModeratorEditListingForm, ContactUsForm, EditBrokerOpenForm, NewBrokerOpenForm
from broker_opens.scripts.csv_importer import file_handler

def property_list(request, day=None, month=None, year=None, location=""):
    date_string = day + '/' + month + '/' + year
    date_object = datetime.datetime.strptime(date_string, "%d/%m/%y").date()
    broker_open = BrokerOpen.objects.get(date__contains=date_object, location__iexact=location.replace('_',' '))
    property_list = broker_open.property_set.all().order_by('sort_order').select_related('listing_agent')
    context = {'broker_open': broker_open, 'property_list': property_list}
    return render(request, 'properties/property_list.html', context)


@login_required
def users_listings(request):
    agent = request.user
    properties = Property.objects.all().filter(listing_agent=agent.id)
    context = {'agent': agent, 'properties': properties}
    return render(request, 'properties/agent_listing.html', context)


def _edit_listing_broker(request, listing):
    if listing.listing_agent.mls_id != request.user.mls_id:
        raise Http404

    if request.method == 'POST':
        form = BrokerEditListingForm(request.POST)
        if form.is_valid():
            listing.__dict__.update(form.cleaned_data)
            listing.edited_by_user = True
            listing.broker_open_id = form.cleaned_data['broker_open'].id
            listing.save()

            messages.add_message(request,messages.INFO, 'Your listing has been updated.')
            return redirect('/my_listings/')
    else:
        form = BrokerEditListingForm(model_to_dict(listing))


    context = {'listing': listing, 'form': form, 'page_title':'Edit Listing - %s'%listing.mls_id}
    return render(request, 'properties/edit_listing_broker.html', context)


def _edit_listing_moderator(request, listing):

    if request.method == 'POST':
        form = ModeratorEditListingForm(request.POST)
        if form.is_valid():
            listing.__dict__.update(form.cleaned_data)
            listing.broker_open_id = form.cleaned_data['broker_open'].id
            listing.save()

            messages.add_message(request,messages.INFO, 'The listing has been updated.')
            return redirect(listing.broker_open.url_to_this)
    else:
        form = ModeratorEditListingForm(model_to_dict(listing))


    context = {'listing': listing, 'form': form, 'page_title':'Edit Listing - %s'%listing.mls_id}
    return render(request, 'properties/edit_listing_moderator.html', context)


@login_required
def edit_listing(request, mls_id):
    listing = get_object_or_404(Property, mls_id=mls_id)
    # make sure user is allowed to edit
    if not request.user.is_moderator:
        return _edit_listing_broker(request, listing)
    else:
        return _edit_listing_moderator(request,listing)



@login_required
def create_users_listing(request):
    if not request.user.user_personal_info_valid:
        messages.add_message(request,messages.INFO, 'Please enter your information before creating a listing.')
        return redirect(reverse('edit_profile'))

    if request.method == 'POST':
        form = BrokerEditListingForm(request.POST)
        if form.is_valid():

            listing = Property.create_property_with_random_id()
            listing.listing_agent_id = request.user.id
            listing.edited_by_user = True
            listing.__dict__.update(form.cleaned_data)
            listing.broker_open_id = form.cleaned_data['broker_open'].id
            listing.sort_order = BrokerOpen.get_next_sort_value(form.cleaned_data['broker_open'].id)
            listing.save()
            messages.add_message(request,messages.INFO, 'Your listing has been created.')
            return redirect('/my_listings/')
    else:
        form = BrokerEditListingForm()
    context = {'form': form, 'page_title':'Create New Listing'}
    return render(request, 'properties/edit_listing_broker.html', context)


@login_required
@user_passes_test(lambda x: x.is_moderator)
def moderator_create_listing(request, broker_open_id):
    broker_open = get_object_or_404(BrokerOpen, pk=broker_open_id)
    if request.method == 'POST':
        form = ModeratorEditListingForm(request.POST)
        if form.is_valid():

            listing = Property.create_property_with_random_id()
            listing.listing_agent_id = request.user.id
            listing.edited_by_user = True
            listing.__dict__.update(form.cleaned_data)
            listing.broker_open_id = form.cleaned_data['broker_open'].id
            listing.sort_order = BrokerOpen.get_next_sort_value(form.cleaned_data['broker_open'].id)
            listing.save()
            messages.add_message(request,messages.INFO, 'Your listing has been created.')
            return redirect('/my_listings/')
    else:
        form = ModeratorEditListingForm(initial={'broker_open':broker_open})
    context = {'form': form, 'page_title':'Create New Listing'}
    return render(request, 'properties/edit_listing_moderator.html', context)


@login_required
@user_passes_test(lambda x: x.is_moderator)
def upload_csv(request, broker_open_id):
    broker_open = get_object_or_404(BrokerOpen, pk=broker_open_id)
    if request.method == 'POST':
        message = ""
        try:
            csv = CsvUpload(file=request.FILES['csv_file'])
            csv.save()

            result = file_handler.process_file(request.FILES['csv_file'], broker_open.id)
            if result['success']:
                message += "<p>" + "Your File Was Successfully Imported." + "</p>"
            else:
                message += "<p>" + "An Error Occured While Importing." + "</p>"
            if result['details']:
                message += "<hr><p>" + result['details'] + "</p>"
            if result['dump']:
                message += "<hr><p>" + result['dump'] + "</p>"
            csv.save()
            csv.details = result['details']
            csv.dump = result['dump']
            csv.save()
        except MultiValueDictKeyError:
            message += "<p>" + "Please Upload a File" + "</p>"

        except:
            message += "<p>" + "An Unknown Error Occured" + "</p>"

        messages.add_message(request,messages.INFO, message)


    return redirect(broker_open.url_to_this)

broker_opens/templates/properties/_edit_listing_form.html
            <form method="POST" action="" id="custom_form">

                <div class="row">
                    <div class="col-sm-12">
                        <div class="form-group{% if form.address.errors %} has-error{% endif %}">
                            <label class="control-label" for="id_address">Address</label>
                            <input type="text" class="form-control" id="id_address" name="address" value="{{ form.address.value|default:"" }}">
                            {% if form.address.errors %}
                            {% for error in form.address.errors %}
                                <span class="help-block">{{ error }}</span>
                            {% endfor %}
                            {% endif %}
                        </div>
                    </div>
                </div>

                <div class="row">
                    <div class="col-sm-12">
                        <div class="form-group{% if form.city.errors %} has-error{% endif %}">
                            <label class="control-label" for="id_city">City</label>
                            <input type="text" class="form-control" id="id_city" name="city" value="{{ form.city.value|default:"" }}">
                            {% if form.city.errors %}
                            {% for error in form.city.errors %}
                                <span class="help-block">{{ error }}</span>
                            {% endfor %}
                            {% endif %}
                        </div>
                    </div>
                </div>

                <div class="row">
                    <div class="col-sm-4">
                        <div class="form-group{% if form.zip_code.errors %} has-error{% endif %}">
                            <label class="control-label" for="id_zip_code">Zip Code</label>
                            <input type="text" class="form-control" id="id_zip_code" name="zip_code" value="{{ form.zip_code.value|default:"" }}">
                            {% if form.zip_code.errors %}
                            {% for error in form.zip_code.errors %}
                                <span class="help-block">{{ error }}</span>
                            {% endfor %}
                            {% endif %}
                        </div>
                    </div>
                    <div class="col-sm-2">
                        <div class="form-group{% if form.beds.errors %} has-error{% endif %}">
                            <label class="control-label" for="id_beds">Beds</label>
                            <input type="text" class="form-control" id="id_beds" name="beds" value="{{ form.beds.value|default:"" }}">
                            {% if form.beds.errors %}
                            {% for error in form.beds.errors %}
                                <span class="help-block">{{ error }}</span>
                            {% endfor %}
                            {% endif %}
                        </div>
                    </div>
                    <div class="col-sm-2">
                        <div class="form-group{% if form.baths.errors %} has-error{% endif %}">
                            <label class="control-label" for="id_baths">Baths</label>
                            <input type="text" class="form-control" id="id_baths" name="baths" value="{{ form.baths.value|default:"" }}">
                            {% if form.baths.errors %}
                            {% for error in form.baths.errors %}
                                <span class="help-block">{{ error }}</span>
                            {% endfor %}
                            {% endif %}
                        </div>
                    </div>
                    <div class="col-sm-4">
                        <div class="form-group{% if form.price.errors %} has-error{% endif %}">
                            <label class="control-label" for="id_price">Price</label>
                            <input type="text" class="form-control" id="id_price" name="price" value="{{ form.price.value|default:"" }}">
                            {% if form.price.errors %}
                            {% for error in form.price.errors %}
                                <span class="help-block">{{ error }}</span>
                            {% endfor %}
                            {% endif %}
                        </div>
                    </div>
                </div>

                <div class="row">
                    <div class="col-sm-12">
                        <div class="form-group{% if form.property_type.errors %} has-error{% endif %}">
                            <label class="control-label" for="id_property_type">Property Type</label>
                            {{ form.property_type}}
                            {% if form.property_type.errors %}
                            {% for error in form.property_type.errors %}
                                <span class="help-block">{{ error }}</span>
                            {% endfor %}
                            {% endif %}
                        </div>
                    </div>
                </div>

                <div class="row">
                    <div class="col-sm-12">
                        <div class="form-group{% if form.broker_open.errors %} has-error{% endif %}">
                            <label class="control-label" for="id_broker_open">Broker Opens List</label>
                            {{ form.broker_open}}
                            {% if form.broker_open.errors %}
                            {% for error in form.broker_open.errors %}
                                <span class="help-block">{{ error }}</span>
                            {% endfor %}
                            {% endif %}
                        </div>
                    </div>
                </div>

                <div class="row">
                    <div class="col-sm-6">
                        <div class="form-group{% if form.start_time.errors %} has-error{% endif %}">
                            <label class="control-label" for="id_start_time">Start Time</label>
                            {{ form.start_time}}
                            {% if form.start_time.errors %}
                            {% for error in form.start_time.errors %}
                                <span class="help-block">{{ error }}</span>
                            {% endfor %}
                            {% endif %}
                        </div>
                    </div>
                    <div class="col-sm-6">
                        <div class="form-group{% if form.end_time.errors %} has-error{% endif %}">
                            <label class="control-label" for="id_end_time">End Time</label>
                            {{ form.end_time}}
                            {% if form.end_time.errors %}
                            {% for error in form.end_time.errors %}
                                <span class="help-block">{{ error }}</span>
                            {% endfor %}
                            {% endif %}
                        </div>
                    </div>

                </div>

broker_opens/templates/properties/_upload_csv_button_and_form.html
    <div class="property-page-buttons">
      <a href="{% url 'moderator_create_listing' broker_open.id %}" class="btn btn-primary btn-large">Add Property</a>
      <a class="btn btn-warning btn-large upload-csv" data-toggle="modal" data-target="#myModal">Upload CSV</a>
    </div>

    <div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" airia-hidden="true">
        <div class="modal-dialog modal-sm">
            <div class="modal-content">

              <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                <h4 class="modal-title" id="myModalLabel">Select a File</h4>
              </div>

              <form method="post" enctype="multipart/form-data" action="{% url 'upload_csv' broker_open.id %}">

              <div class="modal-body">
                <div class="form-group">
                  <label for="CsvFile">CSV File</label>
                  <input type="file" id="CsvFile" name="csv_file">
                  <p class="help-block">Select the file you would like to use.</p>
                </div>
                {% csrf_token %}
              </div>

              <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                <button type="submit" class="btn btn-primary">Go</button>
              </div>

              <form>

            </div>
        </div>
    </div>

broker_opens/templates/properties/edit_listing_moderator.html
{% extends "base.html" %}

{% block title %}Edit Transaction{% endblock %}

{% block content %}

    <div class="container">
        <div class="col-sm-8 col-sm-offset-2">
            <div class="row">
                <div class="col-sm-12">
                    <h2>{{ page_title }}</h2>
                </div>
            </div>
                {% include "properties/_edit_listing_form.html" %}
                <hr>

                 <div class="row">
                    <div class="col-sm-12">
                        <div class="form-group{% if form.listing_agent.errors %} has-error{% endif %}">
                            <label class="control-label" for="id_listing_agent">Listing Agent</label>
                            {{ form.listing_agent}}
                            {% if form.listing_agent.errors %}
                            {% for error in form.listing_agent.errors %}
                                <span class="help-block">{{ error }}</span>
                            {% endfor %}
                            {% endif %}
                        </div>
                    </div>
                </div>

                 <div class="row">
                    <div class="col-sm-6">
                        <div class="form-group{% if form.latitude.errors %} has-error{% endif %}">
                            <label class="control-label" for="id_latitude">Latitude</label>
                            <input type="text" class="form-control" id="id_latitude" name="latitude" value="{{ form.latitude.value|default:"" }}">
                            {% if form.latitude.errors %}
                            {% for error in form.latitude.errors %}
                                <span class="help-block">{{ error }}</span>
                            {% endfor %}
                            {% endif %}
                        </div>
                    </div>
                    <div class="col-sm-6">
                        <div class="form-group{% if form.longitude.errors %} has-error{% endif %}">
                            <label class="control-label" for="id_longitude">Longitude</label>
                            <input type="text" class="form-control" id="id_longitude" name="longitude" value="{{ form.longitude.value|default:"" }}">
                            {% if form.longitude.errors %}
                            {% for error in form.longitude.errors %}
                                <span class="help-block">{{ error }}</span>
                            {% endfor %}
                            {% endif %}
                        </div>
                    </div>
                 </div>
                <div class="row">

                    <div class="col-sm-4">
                        <div class="form-group{% if form.edited_by_user.errors %} has-error{% endif %}">
                            <label class="control-label" for="id_edited_by_user">Edited By User?</label>
                        </div>
                        {{ form.edited_by_user }}
                    </div>
                    <div class="col-sm-4">
                        <div class="form-group{% if form.sort_order.errors %} has-error{% endif %}">
                            <label class="control-label" for="id_sort_order">Sort Order</label>
                            <input type="text" class="form-control" id="id_sort_order" name="sort_order" value="{{ form.sort_order.value|default:"" }}">
                            {% if form.sort_order.errors %}
                            {% for error in form.sort_order.errors %}
                                <span class="help-block">{{ error }}</span>
                            {% endfor %}
                            {% endif %}
                        </div>
                    </div>

                    <div class="col-sm-4">
                        <div class="form-group{% if form.days_on_market.errors %} has-error{% endif %}">
                            <label class="control-label" for="id_days_on_market">Days On Market</label>
                            <input type="text" class="form-control" id="id_days_on_market" name="days_on_market" value="{{ form.days_on_market.value|default:"" }}">
                            {% if form.days_on_market.errors %}
                            {% for error in form.days_on_market.errors %}
                                <span class="help-block">{{ error }}</span>
                            {% endfor %}
                            {% endif %}
                        </div>
                    </div>
                 </div>


                <div class="row">
                    {% csrf_token %}
                    <div class="col-sm-12">
                        <input type="submit" vale="save" class="btn btn-primary btn-lg bottom-space">
                    </div>
                </div>
            </form>

        </div>
    </div>

    <br />


{% endblock   %}